name: interactive_timeline
description: Draggable and zoomable interactive timeline.
version: 1.0.0-dev.2
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    # bloc
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
